In [1]:
import numpy as np

In [2]:
train = np.loadtxt('2d.trn.dat', dtype=str)

In [3]:
train = train[1:]

In [4]:
features_train = train[:,:-1].astype(float)

In [5]:
features_train

array([[ 9.31 , 48.289],
       [13.364, 49.943],
       [ 2.301, 75.125],
       ...,
       [17.546, 77.528],
       [-1.829, 54.649],
       [-4.023, 33.008]])

In [6]:
target_train = train[:,-1:]

In [7]:
target_train

array([['C'],
       ['C'],
       ['B'],
       ...,
       ['C'],
       ['A'],
       ['C']], dtype='<U7')

In [8]:
features_train

array([[ 9.31 , 48.289],
       [13.364, 49.943],
       [ 2.301, 75.125],
       ...,
       [17.546, 77.528],
       [-1.829, 54.649],
       [-4.023, 33.008]])

In [23]:
import random


def split_train_validation(X, y):
    indices = np.arange(X.shape[0], dtype=int)
    random.shuffle(indices)
    split = int(0.8 * X.shape[0])
    train_indices = indices[:split]
    val_indices = indices[split:]

    train_features = X[:, train_indices]
    train_labels = y[:, train_indices]

    val_features = X[:, val_indices]
    val_labels = y[:,val_indices]
    return train_features,train_labels,val_features,val_labels

In [16]:
def ordinal_encoding(y):
    """
    Convert categorical data to numerical.\n
    Example: ['A','A','B','C','C'] -> [0,0,1,2,2].\n
    :param y: class labels. Correct shape (n,)
    :return: numpy array with shape (n,)
    """
    i = 0
    unique_categories = np.unique(y)
    for cat in unique_categories:
        y[y == cat] = i
        i += 1
    return y.astype(int)

In [17]:
train_labels = ordinal_encoding(train_labels)
test_labels = ordinal_encoding(test_labels)

In [11]:
train_data = np.loadtxt('2d.trn.dat', dtype=str)
test_data = np.loadtxt('2d.tst.dat', dtype=str)

train_data = train_data[1:]
test_data = test_data[1:]

(count, dim) = train_data.shape

train_features = train_data[:, :-1].astype(float)
train_labels = train_data[:, -1:].flatten()  # ['A','B','C' .... 'A']
test_features = test_data[:, :-1].astype(float)
test_labels = test_data[:, -1:].flatten()  # ['A','B','C' .... 'A']

train_labels = ordinal_encoding(train_labels)
test_labels = ordinal_encoding(test_labels)

In [21]:
train_labels

array([2, 2, 1, ..., 2, 0, 2])

In [20]:
a = np.array([1, 0, 3])
b = np.zeros((train_labels.size, train_labels.max()+1))
b[np.arange(train_labels.size),train_labels] = 1
b

array([[0., 0., 1.],
       [0., 0., 1.],
       [0., 1., 0.],
       ...,
       [0., 0., 1.],
       [1., 0., 0.],
       [0., 0., 1.]])